// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "ui.h"
#include <stdbool.h>

extern int32_t Angle;
extern int current_angle;
extern bool is_Auto_Running;
extern void Write_Led_PE3(int state);
extern bool auto_mode_1;
extern bool auto_mode_2;
extern bool auto_mode_3;
extern bool start_auto;
void ControlJoint1Servo(lv_event_t * e)
{
	if(is_Auto_Running) {
		// Nếu đang ở chế độ tự động, không cho phép điều khiển thủ công
		return;
	}

	lv_obj_t * slider = lv_event_get_target(e);
	Angle = lv_slider_get_value(slider);
}

void OnOffLED(lv_event_t * e)
{
	lv_obj_t * btn = lv_event_get_target(e);
    
    // Kiểm tra xem nó đang Checked (Bấm xuống) hay Unchecked
    bool is_checked = lv_obj_has_state(btn, LV_STATE_CHECKED);
    
    // Set start_auto để kích hoạt chế độ tự động
    start_auto = is_checked;
    
    // Gọi hàm phần cứng
    if (is_checked) {
        Write_Led_PE3(1); // Gửi lệnh BẬT
    } else {
        Write_Led_PE3(0); // Gửi lệnh TẮT
    }
}

void Mode1_ON(lv_event_t * e)
{
    lv_obj_t * btn = lv_event_get_target(e);
    bool is_checked = lv_obj_has_state(btn, LV_STATE_CHECKED);
    if (is_checked) {
        auto_mode_1 = true;
        auto_mode_2 = false;
        auto_mode_3 = false;
    } else {
        auto_mode_1 = false;
    }
}

void Mode2_ON(lv_event_t * e)
{
	lv_obj_t * btn = lv_event_get_target(e);
    bool is_checked = lv_obj_has_state(btn, LV_STATE_CHECKED);
    if (is_checked) {
        auto_mode_2 = true;
        auto_mode_1 = false;
        auto_mode_3 = false;
    } else {
        auto_mode_2 = false;
    }
}

void Mode3_ON(lv_event_t * e)
{
	lv_obj_t * btn = lv_event_get_target(e);
    bool is_checked = lv_obj_has_state(btn, LV_STATE_CHECKED);
    if (is_checked) {
        auto_mode_3 = true;
        auto_mode_1 = false;
        auto_mode_2 = false;
    } else {
        auto_mode_3 = false;
    }
}

void ResetCount(lv_event_t * e)
{
	// Your code here
}
