// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void ControlJoint1Servo(lv_event_t * e);
void Mode1_ON(lv_event_t * e);
void Mode2_ON(lv_event_t * e);
void Mode3_ON(lv_event_t * e);
void OnOffLED(lv_event_t * e);
void ResetCount(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
