// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_AUTOSCREEN_H
#define UI_AUTOSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_AutoScreen
extern void ui_AutoScreen_screen_init(void);
extern void ui_AutoScreen_screen_destroy(void);
extern lv_obj_t * ui_AutoScreen;
extern lv_obj_t * ui_Image23;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Image24;
extern void ui_event_HomeButton5(lv_event_t * e);
extern lv_obj_t * ui_HomeButton5;
extern void ui_event_Mode1Button(lv_event_t * e);
extern lv_obj_t * ui_Mode1Button;
extern void ui_event_Mode2Button(lv_event_t * e);
extern lv_obj_t * ui_Mode2Button;
extern void ui_event_Mode3Button(lv_event_t * e);
extern lv_obj_t * ui_Mode3Button;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Label23;
extern void ui_event_startstopButton(lv_event_t * e);
extern lv_obj_t * ui_startstopButton;
extern lv_obj_t * ui_settingText3;
extern void ui_event_ViewDataButton1(lv_event_t * e);
extern lv_obj_t * ui_ViewDataButton1;
extern lv_obj_t * ui_viewtext;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

