// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_CalibrationScreen = NULL;
lv_obj_t * ui_Image28 = NULL;
lv_obj_t * ui_Label33 = NULL;
lv_obj_t * ui_Image29 = NULL;
lv_obj_t * ui_HomeButton7 = NULL;
lv_obj_t * ui_startstopButton2 = NULL;
lv_obj_t * ui_settingText4 = NULL;
lv_obj_t * ui_ViewDataButton3 = NULL;
lv_obj_t * ui_viewtext2 = NULL;
lv_obj_t * ui_StartText2 = NULL;
lv_obj_t * ui_StopText2 = NULL;
// event funtions
void ui_event_HomeButton7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MainMenu, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_MainMenu_screen_init);
    }
}

void ui_event_startstopButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        OnOffLED(e);
        _ui_state_modify(ui_ManualButton, LV_STATE_DISABLED, _UI_MODIFY_STATE_TOGGLE);
        _ui_flag_modify(ui_StartText2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_StopText2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}

void ui_event_ViewDataButton3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ViewDataScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ViewDataScreen_screen_init);
    }
}

// build funtions

void ui_CalibrationScreen_screen_init(void)
{
    ui_CalibrationScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_CalibrationScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image28 = lv_image_create(ui_CalibrationScreen);
    lv_image_set_src(ui_Image28, &ui_img_1340268884);
    lv_obj_set_width(ui_Image28, 480);
    lv_obj_set_height(ui_Image28, 320);
    lv_obj_set_align(ui_Image28, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image28, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image28, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_image_recolor(ui_Image28, lv_color_hex(0x404040), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor_opa(ui_Image28, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label33 = lv_label_create(ui_CalibrationScreen);
    lv_obj_set_width(ui_Label33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label33, -149);
    lv_obj_set_y(ui_Label33, 137);
    lv_obj_set_align(ui_Label33, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label33, "HOME");
    lv_obj_set_style_text_color(ui_Label33, lv_color_hex(0xD5CFD3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label33, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image29 = lv_image_create(ui_CalibrationScreen);
    lv_image_set_src(ui_Image29, &ui_img_home_50dp_e3e3e3_fill0_wght400_grad0_opsz48_png);
    lv_obj_set_width(ui_Image29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image29, -194);
    lv_obj_set_y(ui_Image29, 136);
    lv_obj_set_align(ui_Image29, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image29, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image29, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image29, 150);

    ui_HomeButton7 = lv_button_create(ui_CalibrationScreen);
    lv_obj_set_width(ui_HomeButton7, 103);
    lv_obj_set_height(ui_HomeButton7, 34);
    lv_obj_set_x(ui_HomeButton7, -168);
    lv_obj_set_y(ui_HomeButton7, 137);
    lv_obj_set_align(ui_HomeButton7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HomeButton7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_HomeButton7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_HomeButton7, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HomeButton7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HomeButton7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_HomeButton7, lv_color_hex(0x7B7B7B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_HomeButton7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_HomeButton7, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_HomeButton7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_HomeButton7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_startstopButton2 = lv_button_create(ui_CalibrationScreen);
    lv_obj_set_width(ui_startstopButton2, 103);
    lv_obj_set_height(ui_startstopButton2, 34);
    lv_obj_set_x(ui_startstopButton2, 168);
    lv_obj_set_y(ui_startstopButton2, 137);
    lv_obj_set_align(ui_startstopButton2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_startstopButton2, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_startstopButton2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_startstopButton2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_startstopButton2, lv_color_hex(0x217C3C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_startstopButton2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_startstopButton2, lv_color_hex(0x7B7B7B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_startstopButton2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_startstopButton2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_startstopButton2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_startstopButton2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_startstopButton2, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_startstopButton2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_startstopButton2, lv_color_hex(0x9A3333), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_startstopButton2, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_settingText4 = lv_label_create(ui_CalibrationScreen);
    lv_obj_set_width(ui_settingText4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_settingText4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_settingText4, -170);
    lv_obj_set_y(ui_settingText4, -145);
    lv_obj_set_align(ui_settingText4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_settingText4, "CALIBRATION");
    lv_obj_set_style_text_color(ui_settingText4, lv_color_hex(0xC8C8C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_settingText4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_settingText4, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ViewDataButton3 = lv_button_create(ui_CalibrationScreen);
    lv_obj_set_width(ui_ViewDataButton3, 103);
    lv_obj_set_height(ui_ViewDataButton3, 34);
    lv_obj_set_x(ui_ViewDataButton3, 0);
    lv_obj_set_y(ui_ViewDataButton3, 137);
    lv_obj_set_align(ui_ViewDataButton3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ViewDataButton3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ViewDataButton3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ViewDataButton3, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ViewDataButton3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ViewDataButton3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ViewDataButton3, lv_color_hex(0x7B7B7B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ViewDataButton3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ViewDataButton3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ViewDataButton3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ViewDataButton3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_viewtext2 = lv_label_create(ui_CalibrationScreen);
    lv_obj_set_width(ui_viewtext2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_viewtext2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_viewtext2, 0);
    lv_obj_set_y(ui_viewtext2, 137);
    lv_obj_set_align(ui_viewtext2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_viewtext2, "VIEWDATA");
    lv_obj_set_style_text_color(ui_viewtext2, lv_color_hex(0xD5CFD3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_viewtext2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StartText2 = lv_label_create(ui_CalibrationScreen);
    lv_obj_set_width(ui_StartText2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StartText2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_StartText2, 168);
    lv_obj_set_y(ui_StartText2, 137);
    lv_obj_set_align(ui_StartText2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_StartText2, "START");
    lv_obj_set_style_text_color(ui_StartText2, lv_color_hex(0xF9F9F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_StartText2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StopText2 = lv_label_create(ui_CalibrationScreen);
    lv_obj_set_width(ui_StopText2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StopText2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_StopText2, 168);
    lv_obj_set_y(ui_StopText2, 137);
    lv_obj_set_align(ui_StopText2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_StopText2, "STOP");
    lv_obj_add_flag(ui_StopText2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_StopText2, lv_color_hex(0xD5CFD3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_StopText2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_HomeButton7, ui_event_HomeButton7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_startstopButton2, ui_event_startstopButton2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ViewDataButton3, ui_event_ViewDataButton3, LV_EVENT_ALL, NULL);

}

void ui_CalibrationScreen_screen_destroy(void)
{
    if(ui_CalibrationScreen) lv_obj_del(ui_CalibrationScreen);

    // NULL screen variables
    ui_CalibrationScreen = NULL;
    ui_Image28 = NULL;
    ui_Label33 = NULL;
    ui_Image29 = NULL;
    ui_HomeButton7 = NULL;
    ui_startstopButton2 = NULL;
    ui_settingText4 = NULL;
    ui_ViewDataButton3 = NULL;
    ui_viewtext2 = NULL;
    ui_StartText2 = NULL;
    ui_StopText2 = NULL;

}
