// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_CALIBRATIONSCREEN_H
#define UI_CALIBRATIONSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_CalibrationScreen
extern void ui_CalibrationScreen_screen_init(void);
extern void ui_CalibrationScreen_screen_destroy(void);
extern lv_obj_t * ui_CalibrationScreen;
extern lv_obj_t * ui_Image28;
extern lv_obj_t * ui_Label33;
extern lv_obj_t * ui_Image29;
extern void ui_event_HomeButton7(lv_event_t * e);
extern lv_obj_t * ui_HomeButton7;
extern void ui_event_startstopButton2(lv_event_t * e);
extern lv_obj_t * ui_startstopButton2;
extern lv_obj_t * ui_settingText4;
extern void ui_event_ViewDataButton3(lv_event_t * e);
extern lv_obj_t * ui_ViewDataButton3;
extern lv_obj_t * ui_viewtext2;
extern lv_obj_t * ui_StartText2;
extern lv_obj_t * ui_StopText2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

