// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_INFOSCREEN_H
#define UI_INFOSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_InfoScreen
extern void ui_InfoScreen_screen_init(void);
extern void ui_InfoScreen_screen_destroy(void);
extern lv_obj_t * ui_InfoScreen;
extern lv_obj_t * ui_Image19;
extern lv_obj_t * ui_settingText2;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Image21;
extern void ui_event_BackButton(lv_event_t * e);
extern lv_obj_t * ui_BackButton;
extern lv_obj_t * ui_Image18;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label19;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

