// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_MAINMENU_H
#define UI_MAINMENU_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MainMenu
extern void ui_MainMenu_screen_init(void);
extern void ui_MainMenu_screen_destroy(void);
extern lv_obj_t * ui_MainMenu;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_AutoIcon;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_AutoText;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Image11;
extern void ui_event_AutoButton(lv_event_t * e);
extern lv_obj_t * ui_AutoButton;
extern void ui_event_ManualButton(lv_event_t * e);
extern lv_obj_t * ui_ManualButton;
extern lv_obj_t * ui_CalibButton;
extern lv_obj_t * ui_HandEyeButton;
extern void ui_event_ViewDataButton(lv_event_t * e);
extern lv_obj_t * ui_ViewDataButton;
extern lv_obj_t * ui_CustomizeButton;
extern lv_obj_t * ui_PointButton;
extern void ui_event_SettingButton(lv_event_t * e);
extern lv_obj_t * ui_SettingButton;
extern lv_obj_t * ui_HomeButton;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

