// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_MainMenu = NULL;
lv_obj_t * ui_background = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_AutoButton = NULL;
lv_obj_t * ui_AutoIcon = NULL;
lv_obj_t * ui_AutoText = NULL;
lv_obj_t * ui_ManualButton = NULL;
lv_obj_t * ui_manualIcon = NULL;
lv_obj_t * ui_manualtext = NULL;
lv_obj_t * ui_CalibButton = NULL;
lv_obj_t * ui_calibIcon = NULL;
lv_obj_t * ui_calibtext = NULL;
lv_obj_t * ui_HandEyeButton = NULL;
lv_obj_t * ui_handeyeIcon = NULL;
lv_obj_t * ui_handeyetext = NULL;
lv_obj_t * ui_ViewDataButton = NULL;
lv_obj_t * ui_viewdataIcon = NULL;
lv_obj_t * ui_Viewtextt = NULL;
lv_obj_t * ui_CustomizeButton = NULL;
lv_obj_t * ui_customIcon = NULL;
lv_obj_t * ui_customtext = NULL;
lv_obj_t * ui_PointButton = NULL;
lv_obj_t * ui_pointteachIcon = NULL;
lv_obj_t * ui_pointtext = NULL;
lv_obj_t * ui_SettingButton = NULL;
lv_obj_t * ui_settingicon = NULL;
lv_obj_t * ui_SettingTextt = NULL;
// event funtions
void ui_event_AutoButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_AutoScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_AutoScreen_screen_init);
    }
}

void ui_event_ManualButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ManualScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_ManualScreen_screen_init);
    }
}

void ui_event_CalibButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_CalibrationScreen, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_CalibrationScreen_screen_init);
    }
}

void ui_event_ViewDataButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ViewDataScreen, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_ViewDataScreen_screen_init);
    }
}

void ui_event_SettingButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SettingScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_SettingScreen_screen_init);
    }
}

// build funtions

void ui_MainMenu_screen_init(void)
{
    ui_MainMenu = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_MainMenu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_background = lv_image_create(ui_MainMenu);
    lv_image_set_src(ui_background, &ui_img_1340268884);
    lv_obj_set_width(ui_background, 480);
    lv_obj_set_height(ui_background, 320);
    lv_obj_set_align(ui_background, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_background, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_background, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_image_recolor(ui_background, lv_color_hex(0x404040), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor_opa(ui_background, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_MainMenu);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -120);
    lv_obj_set_y(ui_Label3, -145);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "ROBOT ARM CONTROL PANEL");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xC8C8C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AutoButton = lv_button_create(ui_MainMenu);
    lv_obj_set_width(ui_AutoButton, 100);
    lv_obj_set_height(ui_AutoButton, 85);
    lv_obj_set_x(ui_AutoButton, -170);
    lv_obj_set_y(ui_AutoButton, -60);
    lv_obj_set_align(ui_AutoButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AutoButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_AutoButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_AutoButton, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_AutoButton, lv_color_hex(0x2FA3E4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AutoButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_AutoButton, lv_color_hex(0x141313), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_AutoButton, LV_GRAD_DIR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_AutoButton, lv_color_hex(0x868485), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_AutoButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_AutoButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_AutoButton, lv_color_hex(0x5E5A5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_AutoButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AutoIcon = lv_image_create(ui_AutoButton);
    lv_image_set_src(ui_AutoIcon, &ui_img_play_circle_50dp_e3e3e3_fill0_wght400_grad0_opsz48_png);
    lv_obj_set_width(ui_AutoIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AutoIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AutoIcon, 0);
    lv_obj_set_y(ui_AutoIcon, -10);
    lv_obj_set_align(ui_AutoIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AutoIcon, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_AutoIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_AutoIcon, 230);

    ui_AutoText = lv_label_create(ui_AutoButton);
    lv_obj_set_width(ui_AutoText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AutoText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AutoText, 0);
    lv_obj_set_y(ui_AutoText, 25);
    lv_obj_set_align(ui_AutoText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AutoText, "AUTO RUN");
    lv_obj_set_style_text_color(ui_AutoText, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AutoText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AutoText, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ManualButton = lv_button_create(ui_MainMenu);
    lv_obj_set_width(ui_ManualButton, 100);
    lv_obj_set_height(ui_ManualButton, 85);
    lv_obj_set_x(ui_ManualButton, -57);
    lv_obj_set_y(ui_ManualButton, -60);
    lv_obj_set_align(ui_ManualButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ManualButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ManualButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ManualButton, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ManualButton, lv_color_hex(0x2FA3E4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ManualButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ManualButton, lv_color_hex(0x141313), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ManualButton, LV_GRAD_DIR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ManualButton, lv_color_hex(0x868485), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ManualButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ManualButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ManualButton, lv_color_hex(0x5E5A5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ManualButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_manualIcon = lv_image_create(ui_ManualButton);
    lv_image_set_src(ui_manualIcon, &ui_img_back_hand_50dp_e3e3e3_fill0_wght400_grad0_opsz48_png);
    lv_obj_set_width(ui_manualIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_manualIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_manualIcon, 0);
    lv_obj_set_y(ui_manualIcon, -10);
    lv_obj_set_align(ui_manualIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_manualIcon, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_manualIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_manualIcon, 230);

    ui_manualtext = lv_label_create(ui_ManualButton);
    lv_obj_set_width(ui_manualtext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_manualtext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_manualtext, 0);
    lv_obj_set_y(ui_manualtext, 25);
    lv_obj_set_align(ui_manualtext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_manualtext, "MANUAL");
    lv_obj_set_style_text_color(ui_manualtext, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_manualtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_manualtext, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CalibButton = lv_button_create(ui_MainMenu);
    lv_obj_set_width(ui_CalibButton, 100);
    lv_obj_set_height(ui_CalibButton, 85);
    lv_obj_set_x(ui_CalibButton, 57);
    lv_obj_set_y(ui_CalibButton, -60);
    lv_obj_set_align(ui_CalibButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CalibButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_CalibButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_CalibButton, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CalibButton, lv_color_hex(0x2FA3E4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CalibButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_CalibButton, lv_color_hex(0x141313), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_CalibButton, LV_GRAD_DIR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_CalibButton, lv_color_hex(0x868485), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_CalibButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_CalibButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_CalibButton, lv_color_hex(0x5E5A5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_CalibButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_calibIcon = lv_image_create(ui_CalibButton);
    lv_image_set_src(ui_calibIcon, &ui_img_center_focus_strong_50dp_e3e3e3_fill0_wght400_grad0_opsz48_png);
    lv_obj_set_width(ui_calibIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_calibIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_calibIcon, 0);
    lv_obj_set_y(ui_calibIcon, -10);
    lv_obj_set_align(ui_calibIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_calibIcon, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_calibIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_calibIcon, 238);

    ui_calibtext = lv_label_create(ui_CalibButton);
    lv_obj_set_width(ui_calibtext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_calibtext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_calibtext, 0);
    lv_obj_set_y(ui_calibtext, 25);
    lv_obj_set_align(ui_calibtext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_calibtext, "CALIBRATION");
    lv_obj_set_style_text_color(ui_calibtext, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_calibtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_calibtext, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HandEyeButton = lv_button_create(ui_MainMenu);
    lv_obj_set_width(ui_HandEyeButton, 100);
    lv_obj_set_height(ui_HandEyeButton, 85);
    lv_obj_set_x(ui_HandEyeButton, -170);
    lv_obj_set_y(ui_HandEyeButton, 45);
    lv_obj_set_align(ui_HandEyeButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HandEyeButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_HandEyeButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_HandEyeButton, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HandEyeButton, lv_color_hex(0x2FA3E4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HandEyeButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_HandEyeButton, lv_color_hex(0x141313), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_HandEyeButton, LV_GRAD_DIR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_HandEyeButton, lv_color_hex(0x868485), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_HandEyeButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_HandEyeButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_HandEyeButton, lv_color_hex(0x5E5A5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_HandEyeButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_handeyeIcon = lv_image_create(ui_HandEyeButton);
    lv_image_set_src(ui_handeyeIcon, &ui_img_multimodal_hand_eye_50dp_e3e3e3_fill0_wght400_grad0_opsz48_png);
    lv_obj_set_width(ui_handeyeIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_handeyeIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_handeyeIcon, 0);
    lv_obj_set_y(ui_handeyeIcon, -10);
    lv_obj_set_align(ui_handeyeIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_handeyeIcon, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_handeyeIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_handeyeIcon, 230);

    ui_handeyetext = lv_label_create(ui_HandEyeButton);
    lv_obj_set_width(ui_handeyetext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_handeyetext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_handeyetext, 0);
    lv_obj_set_y(ui_handeyetext, 25);
    lv_obj_set_align(ui_handeyetext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_handeyetext, "HAND-EYE");
    lv_obj_set_style_text_color(ui_handeyetext, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_handeyetext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_handeyetext, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ViewDataButton = lv_button_create(ui_MainMenu);
    lv_obj_set_width(ui_ViewDataButton, 100);
    lv_obj_set_height(ui_ViewDataButton, 85);
    lv_obj_set_x(ui_ViewDataButton, -57);
    lv_obj_set_y(ui_ViewDataButton, 45);
    lv_obj_set_align(ui_ViewDataButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ViewDataButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ViewDataButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ViewDataButton, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ViewDataButton, lv_color_hex(0x2FA3E4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ViewDataButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ViewDataButton, lv_color_hex(0x141313), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ViewDataButton, LV_GRAD_DIR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ViewDataButton, lv_color_hex(0x868485), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ViewDataButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ViewDataButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ViewDataButton, lv_color_hex(0x5E5A5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ViewDataButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_viewdataIcon = lv_image_create(ui_ViewDataButton);
    lv_image_set_src(ui_viewdataIcon, &ui_img_data_table_50dp_e3e3e3_fill0_wght400_grad0_opsz48_png);
    lv_obj_set_width(ui_viewdataIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_viewdataIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_viewdataIcon, 0);
    lv_obj_set_y(ui_viewdataIcon, -10);
    lv_obj_set_align(ui_viewdataIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_viewdataIcon, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_viewdataIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_viewdataIcon, 230);

    ui_Viewtextt = lv_label_create(ui_ViewDataButton);
    lv_obj_set_width(ui_Viewtextt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Viewtextt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Viewtextt, 0);
    lv_obj_set_y(ui_Viewtextt, 25);
    lv_obj_set_align(ui_Viewtextt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Viewtextt, "VIEW DATA");
    lv_obj_set_style_text_color(ui_Viewtextt, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Viewtextt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Viewtextt, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CustomizeButton = lv_button_create(ui_MainMenu);
    lv_obj_set_width(ui_CustomizeButton, 100);
    lv_obj_set_height(ui_CustomizeButton, 85);
    lv_obj_set_x(ui_CustomizeButton, 57);
    lv_obj_set_y(ui_CustomizeButton, 45);
    lv_obj_set_align(ui_CustomizeButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CustomizeButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_CustomizeButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_CustomizeButton, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CustomizeButton, lv_color_hex(0x2FA3E4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CustomizeButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_CustomizeButton, lv_color_hex(0x141313), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_CustomizeButton, LV_GRAD_DIR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_CustomizeButton, lv_color_hex(0x868485), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_CustomizeButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_CustomizeButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_CustomizeButton, lv_color_hex(0x5E5A5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_CustomizeButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_customIcon = lv_image_create(ui_CustomizeButton);
    lv_image_set_src(ui_customIcon, &ui_img_dashboard_customize_50dp_e3e3e3_fill0_wght400_grad0_opsz48_png);
    lv_obj_set_width(ui_customIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_customIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_customIcon, 0);
    lv_obj_set_y(ui_customIcon, -10);
    lv_obj_set_align(ui_customIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_customIcon, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_customIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_customIcon, 230);

    ui_customtext = lv_label_create(ui_CustomizeButton);
    lv_obj_set_width(ui_customtext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_customtext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_customtext, 0);
    lv_obj_set_y(ui_customtext, 25);
    lv_obj_set_align(ui_customtext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_customtext, "CUSTOMIZE");
    lv_obj_set_style_text_color(ui_customtext, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_customtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_customtext, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PointButton = lv_button_create(ui_MainMenu);
    lv_obj_set_width(ui_PointButton, 100);
    lv_obj_set_height(ui_PointButton, 85);
    lv_obj_set_x(ui_PointButton, 170);
    lv_obj_set_y(ui_PointButton, -60);
    lv_obj_set_align(ui_PointButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PointButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_PointButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PointButton, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PointButton, lv_color_hex(0x2FA3E4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PointButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_PointButton, lv_color_hex(0x141313), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_PointButton, LV_GRAD_DIR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PointButton, lv_color_hex(0x868485), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PointButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PointButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_PointButton, lv_color_hex(0x5E5A5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_PointButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pointteachIcon = lv_image_create(ui_PointButton);
    lv_image_set_src(ui_pointteachIcon, &ui_img_location_on_50dp_e3e3e3_fill0_wght400_grad0_opsz48_png);
    lv_obj_set_width(ui_pointteachIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pointteachIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pointteachIcon, 0);
    lv_obj_set_y(ui_pointteachIcon, -10);
    lv_obj_set_align(ui_pointteachIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pointteachIcon, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_pointteachIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_pointteachIcon, 230);

    ui_pointtext = lv_label_create(ui_PointButton);
    lv_obj_set_width(ui_pointtext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pointtext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pointtext, 0);
    lv_obj_set_y(ui_pointtext, 25);
    lv_obj_set_align(ui_pointtext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pointtext, "POINT TEACH");
    lv_obj_set_style_text_color(ui_pointtext, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pointtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pointtext, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingButton = lv_button_create(ui_MainMenu);
    lv_obj_set_width(ui_SettingButton, 100);
    lv_obj_set_height(ui_SettingButton, 85);
    lv_obj_set_x(ui_SettingButton, 170);
    lv_obj_set_y(ui_SettingButton, 45);
    lv_obj_set_align(ui_SettingButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_SettingButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SettingButton, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SettingButton, lv_color_hex(0x2FA3E4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_SettingButton, lv_color_hex(0x141313), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_SettingButton, LV_GRAD_DIR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SettingButton, lv_color_hex(0x868485), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SettingButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SettingButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SettingButton, lv_color_hex(0x5E5A5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SettingButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settingicon = lv_image_create(ui_SettingButton);
    lv_image_set_src(ui_settingicon, &ui_img_settings_50dp_e3e3e3_fill0_wght400_grad0_opsz48_png);
    lv_obj_set_width(ui_settingicon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_settingicon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_settingicon, 0);
    lv_obj_set_y(ui_settingicon, -10);
    lv_obj_set_align(ui_settingicon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_settingicon, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_settingicon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_settingicon, 230);

    ui_SettingTextt = lv_label_create(ui_SettingButton);
    lv_obj_set_width(ui_SettingTextt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingTextt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SettingTextt, 0);
    lv_obj_set_y(ui_SettingTextt, 25);
    lv_obj_set_align(ui_SettingTextt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SettingTextt, "SETTING");
    lv_obj_set_style_text_color(ui_SettingTextt, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SettingTextt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SettingTextt, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_AutoButton, ui_event_AutoButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ManualButton, ui_event_ManualButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CalibButton, ui_event_CalibButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ViewDataButton, ui_event_ViewDataButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SettingButton, ui_event_SettingButton, LV_EVENT_ALL, NULL);

}

void ui_MainMenu_screen_destroy(void)
{
    if(ui_MainMenu) lv_obj_del(ui_MainMenu);

    // NULL screen variables
    ui_MainMenu = NULL;
    ui_background = NULL;
    ui_Label3 = NULL;
    ui_AutoButton = NULL;
    ui_AutoIcon = NULL;
    ui_AutoText = NULL;
    ui_ManualButton = NULL;
    ui_manualIcon = NULL;
    ui_manualtext = NULL;
    ui_CalibButton = NULL;
    ui_calibIcon = NULL;
    ui_calibtext = NULL;
    ui_HandEyeButton = NULL;
    ui_handeyeIcon = NULL;
    ui_handeyetext = NULL;
    ui_ViewDataButton = NULL;
    ui_viewdataIcon = NULL;
    ui_Viewtextt = NULL;
    ui_CustomizeButton = NULL;
    ui_customIcon = NULL;
    ui_customtext = NULL;
    ui_PointButton = NULL;
    ui_pointteachIcon = NULL;
    ui_pointtext = NULL;
    ui_SettingButton = NULL;
    ui_settingicon = NULL;
    ui_SettingTextt = NULL;

}
