// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_MANUALSCREEN_H
#define UI_MANUALSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ManualScreen
extern void ui_ManualScreen_screen_init(void);
extern void ui_ManualScreen_screen_destroy(void);
extern lv_obj_t * ui_ManualScreen;
extern lv_obj_t * ui_Image12;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Image13;
extern void ui_event_HomeButton2(lv_event_t * e);
extern lv_obj_t * ui_HomeButton2;
extern lv_obj_t * ui_Label13;
extern void ui_event_Slider1(lv_event_t * e);
extern lv_obj_t * ui_Slider1;
extern lv_obj_t * ui_Slider2;
extern lv_obj_t * ui_Slider3;
extern lv_obj_t * ui_Slider4;
extern lv_obj_t * ui_Slider5;
extern lv_obj_t * ui_Slider6;
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_Label29;
extern lv_obj_t * ui_Label30;
extern lv_obj_t * ui_Label31;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

