// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_MAINMENU_H
#define UI_MAINMENU_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MainMenu
extern void ui_MainMenu_screen_init(void);
extern void ui_MainMenu_screen_destroy(void);
extern lv_obj_t * ui_MainMenu;
extern lv_obj_t * ui_background;
extern lv_obj_t * ui_Label3;
extern void ui_event_AutoButton(lv_event_t * e);
extern lv_obj_t * ui_AutoButton;
extern lv_obj_t * ui_AutoIcon;
extern lv_obj_t * ui_AutoText;
extern void ui_event_ManualButton(lv_event_t * e);
extern lv_obj_t * ui_ManualButton;
extern lv_obj_t * ui_manualIcon;
extern lv_obj_t * ui_manualtext;
extern void ui_event_CalibButton(lv_event_t * e);
extern lv_obj_t * ui_CalibButton;
extern lv_obj_t * ui_calibIcon;
extern lv_obj_t * ui_calibtext;
extern lv_obj_t * ui_HandEyeButton;
extern lv_obj_t * ui_handeyeIcon;
extern lv_obj_t * ui_handeyetext;
extern void ui_event_ViewDataButton(lv_event_t * e);
extern lv_obj_t * ui_ViewDataButton;
extern lv_obj_t * ui_viewdataIcon;
extern lv_obj_t * ui_Viewtextt;
extern lv_obj_t * ui_CustomizeButton;
extern lv_obj_t * ui_customIcon;
extern lv_obj_t * ui_customtext;
extern lv_obj_t * ui_PointButton;
extern lv_obj_t * ui_pointteachIcon;
extern lv_obj_t * ui_pointtext;
extern void ui_event_SettingButton(lv_event_t * e);
extern lv_obj_t * ui_SettingButton;
extern lv_obj_t * ui_settingicon;
extern lv_obj_t * ui_SettingTextt;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

