// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_SettingScreen = NULL;
lv_obj_t * ui_Image14 = NULL;
lv_obj_t * ui_settingText = NULL;
lv_obj_t * ui_Label16 = NULL;
lv_obj_t * ui_Image15 = NULL;
lv_obj_t * ui_Image16 = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_Image17 = NULL;
lv_obj_t * ui_SecurityText = NULL;
lv_obj_t * ui_LicenseText = NULL;
lv_obj_t * ui_InfoText = NULL;
lv_obj_t * ui_SecurityButton = NULL;
lv_obj_t * ui_LicenseButton = NULL;
lv_obj_t * ui_InfoButton = NULL;
lv_obj_t * ui_HomeButton3 = NULL;
// event funtions
void ui_event_InfoButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_InfoScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_InfoScreen_screen_init);
    }
}

void ui_event_HomeButton3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MainMenu, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_MainMenu_screen_init);
    }
}

// build funtions

void ui_SettingScreen_screen_init(void)
{
    ui_SettingScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_SettingScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image14 = lv_image_create(ui_SettingScreen);
    lv_image_set_src(ui_Image14, &ui_img_1340268884);
    lv_obj_set_width(ui_Image14, 480);
    lv_obj_set_height(ui_Image14, 320);
    lv_obj_set_align(ui_Image14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image14, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_image_recolor(ui_Image14, lv_color_hex(0x404040), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor_opa(ui_Image14, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settingText = lv_label_create(ui_SettingScreen);
    lv_obj_set_width(ui_settingText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_settingText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_settingText, -170);
    lv_obj_set_y(ui_settingText, -145);
    lv_obj_set_align(ui_settingText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_settingText, "SETTING MODE");
    lv_obj_set_style_text_color(ui_settingText, lv_color_hex(0xC8C8C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_settingText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_settingText, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_SettingScreen);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, -149);
    lv_obj_set_y(ui_Label16, 137);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "HOME");
    lv_obj_set_style_text_color(ui_Label16, lv_color_hex(0xD5CFD3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image15 = lv_image_create(ui_SettingScreen);
    lv_image_set_src(ui_Image15, &ui_img_home_50dp_e3e3e3_fill0_wght400_grad0_opsz48_png);
    lv_obj_set_width(ui_Image15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image15, -194);
    lv_obj_set_y(ui_Image15, 136);
    lv_obj_set_align(ui_Image15, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image15, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image15, 150);

    ui_Image16 = lv_image_create(ui_SettingScreen);
    lv_image_set_src(ui_Image16, &ui_img_security_50dp_e3e3e3_fill0_wght400_grad0_opsz48_png);
    lv_obj_set_width(ui_Image16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image16, -120);
    lv_obj_set_y(ui_Image16, -10);
    lv_obj_set_align(ui_Image16, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image16, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image16, 230);

    ui_Image1 = lv_image_create(ui_SettingScreen);
    lv_image_set_src(ui_Image1, &ui_img_license_50dp_e3e3e3_fill0_wght400_grad0_opsz48_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image1, 0);
    lv_obj_set_y(ui_Image1, -10);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image1, 230);

    ui_Image17 = lv_image_create(ui_SettingScreen);
    lv_image_set_src(ui_Image17, &ui_img_info_50dp_e3e3e3_fill0_wght400_grad0_opsz48_png);
    lv_obj_set_width(ui_Image17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image17, 120);
    lv_obj_set_y(ui_Image17, -10);
    lv_obj_set_align(ui_Image17, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image17, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image17, 230);

    ui_SecurityText = lv_label_create(ui_SettingScreen);
    lv_obj_set_width(ui_SecurityText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SecurityText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SecurityText, -120);
    lv_obj_set_y(ui_SecurityText, 30);
    lv_obj_set_align(ui_SecurityText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SecurityText, "SECURITY");
    lv_obj_set_style_text_color(ui_SecurityText, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SecurityText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SecurityText, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LicenseText = lv_label_create(ui_SettingScreen);
    lv_obj_set_width(ui_LicenseText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LicenseText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LicenseText, 0);
    lv_obj_set_y(ui_LicenseText, 30);
    lv_obj_set_align(ui_LicenseText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LicenseText, "LICENSE");
    lv_obj_set_style_text_color(ui_LicenseText, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LicenseText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LicenseText, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_InfoText = lv_label_create(ui_SettingScreen);
    lv_obj_set_width(ui_InfoText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_InfoText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_InfoText, 120);
    lv_obj_set_y(ui_InfoText, 30);
    lv_obj_set_align(ui_InfoText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_InfoText, "ABOUT");
    lv_obj_set_style_text_color(ui_InfoText, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_InfoText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_InfoText, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SecurityButton = lv_button_create(ui_SettingScreen);
    lv_obj_set_width(ui_SecurityButton, 100);
    lv_obj_set_height(ui_SecurityButton, 85);
    lv_obj_set_x(ui_SecurityButton, -120);
    lv_obj_set_y(ui_SecurityButton, 0);
    lv_obj_set_align(ui_SecurityButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SecurityButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_SecurityButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SecurityButton, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SecurityButton, lv_color_hex(0x2FA3E4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SecurityButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_SecurityButton, lv_color_hex(0x141313), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_SecurityButton, LV_GRAD_DIR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SecurityButton, lv_color_hex(0x868485), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SecurityButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SecurityButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SecurityButton, lv_color_hex(0x5E5A5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SecurityButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LicenseButton = lv_button_create(ui_SettingScreen);
    lv_obj_set_width(ui_LicenseButton, 100);
    lv_obj_set_height(ui_LicenseButton, 85);
    lv_obj_set_align(ui_LicenseButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LicenseButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_LicenseButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_LicenseButton, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LicenseButton, lv_color_hex(0x2FA3E4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LicenseButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_LicenseButton, lv_color_hex(0x141313), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_LicenseButton, LV_GRAD_DIR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LicenseButton, lv_color_hex(0x868485), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LicenseButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_LicenseButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_LicenseButton, lv_color_hex(0x5E5A5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_LicenseButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_InfoButton = lv_button_create(ui_SettingScreen);
    lv_obj_set_width(ui_InfoButton, 100);
    lv_obj_set_height(ui_InfoButton, 85);
    lv_obj_set_x(ui_InfoButton, 120);
    lv_obj_set_y(ui_InfoButton, 0);
    lv_obj_set_align(ui_InfoButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_InfoButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_InfoButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_InfoButton, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_InfoButton, lv_color_hex(0x2FA3E4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_InfoButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_InfoButton, lv_color_hex(0x141313), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_InfoButton, LV_GRAD_DIR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_InfoButton, lv_color_hex(0x868485), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_InfoButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_InfoButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_InfoButton, lv_color_hex(0x5E5A5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_InfoButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeButton3 = lv_button_create(ui_SettingScreen);
    lv_obj_set_width(ui_HomeButton3, 103);
    lv_obj_set_height(ui_HomeButton3, 34);
    lv_obj_set_x(ui_HomeButton3, -168);
    lv_obj_set_y(ui_HomeButton3, 137);
    lv_obj_set_align(ui_HomeButton3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HomeButton3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_HomeButton3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_HomeButton3, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HomeButton3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HomeButton3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_HomeButton3, lv_color_hex(0x7B7B7B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_HomeButton3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_HomeButton3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_HomeButton3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_HomeButton3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_InfoButton, ui_event_InfoButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HomeButton3, ui_event_HomeButton3, LV_EVENT_ALL, NULL);

}

void ui_SettingScreen_screen_destroy(void)
{
    if(ui_SettingScreen) lv_obj_del(ui_SettingScreen);

    // NULL screen variables
    ui_SettingScreen = NULL;
    ui_Image14 = NULL;
    ui_settingText = NULL;
    ui_Label16 = NULL;
    ui_Image15 = NULL;
    ui_Image16 = NULL;
    ui_Image1 = NULL;
    ui_Image17 = NULL;
    ui_SecurityText = NULL;
    ui_LicenseText = NULL;
    ui_InfoText = NULL;
    ui_SecurityButton = NULL;
    ui_LicenseButton = NULL;
    ui_InfoButton = NULL;
    ui_HomeButton3 = NULL;

}
