// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_SETTINGSCREEN_H
#define UI_SETTINGSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SettingScreen
extern void ui_SettingScreen_screen_init(void);
extern void ui_SettingScreen_screen_destroy(void);
extern lv_obj_t * ui_SettingScreen;
extern lv_obj_t * ui_Image14;
extern lv_obj_t * ui_settingText;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Image15;
extern lv_obj_t * ui_Image16;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Image17;
extern lv_obj_t * ui_SecurityText;
extern lv_obj_t * ui_LicenseText;
extern lv_obj_t * ui_InfoText;
extern lv_obj_t * ui_SecurityButton;
extern lv_obj_t * ui_LicenseButton;
extern void ui_event_InfoButton(lv_event_t * e);
extern lv_obj_t * ui_InfoButton;
extern void ui_event_HomeButton3(lv_event_t * e);
extern lv_obj_t * ui_HomeButton3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

