// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_ViewDataScreen = NULL;
lv_obj_t * ui_Image25 = NULL;
lv_obj_t * ui_ViewDatatext = NULL;
lv_obj_t * ui_SP1 = NULL;
lv_obj_t * ui_SP2 = NULL;
lv_obj_t * ui_SP3 = NULL;
lv_obj_t * ui_NumSP1 = NULL;
lv_obj_t * ui_NumSP2 = NULL;
lv_obj_t * ui_NumSP3 = NULL;
lv_obj_t * ui_Label25 = NULL;
lv_obj_t * ui_HomeButton6 = NULL;
lv_obj_t * ui_Image26 = NULL;
lv_obj_t * ui_ResetButton = NULL;
lv_obj_t * ui_ResetText = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_ResetButton2 = NULL;
lv_obj_t * ui_ResetButton1 = NULL;
lv_obj_t * ui_Label24 = NULL;
lv_obj_t * ui_ResetText1 = NULL;
lv_obj_t * ui_ResetText3 = NULL;
// event funtions
void ui_event_HomeButton6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MainMenu, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_MainMenu_screen_init);
    }
}

void ui_event_ResetButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Panel1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_state_modify(ui_HomeButton6, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
        _ui_state_modify(ui_ResetButton, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
    }
}

void ui_event_ResetButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ResetCount(e);
        _ui_flag_modify(ui_Panel1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_state_modify(ui_HomeButton6, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_ResetButton, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
    }
}

void ui_event_ResetButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Panel1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_state_modify(ui_HomeButton6, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_ResetButton, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
    }
}

// build funtions

void ui_ViewDataScreen_screen_init(void)
{
    ui_ViewDataScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ViewDataScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image25 = lv_image_create(ui_ViewDataScreen);
    lv_image_set_src(ui_Image25, &ui_img_1340268884);
    lv_obj_set_width(ui_Image25, 480);
    lv_obj_set_height(ui_Image25, 320);
    lv_obj_set_align(ui_Image25, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image25, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image25, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_image_recolor(ui_Image25, lv_color_hex(0x404040), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor_opa(ui_Image25, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ViewDatatext = lv_label_create(ui_ViewDataScreen);
    lv_obj_set_width(ui_ViewDatatext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ViewDatatext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ViewDatatext, -180);
    lv_obj_set_y(ui_ViewDatatext, -145);
    lv_obj_set_align(ui_ViewDatatext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ViewDatatext, "VIEW DATA");
    lv_obj_set_style_text_color(ui_ViewDatatext, lv_color_hex(0xC8C8C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ViewDatatext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ViewDatatext, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SP1 = lv_label_create(ui_ViewDataScreen);
    lv_obj_set_width(ui_SP1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SP1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SP1, -120);
    lv_obj_set_y(ui_SP1, -30);
    lv_obj_set_align(ui_SP1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SP1, "SP1");
    lv_obj_set_style_text_color(ui_SP1, lv_color_hex(0xE8EEEF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SP1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SP2 = lv_label_create(ui_ViewDataScreen);
    lv_obj_set_width(ui_SP2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SP2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SP2, 0);
    lv_obj_set_y(ui_SP2, -30);
    lv_obj_set_align(ui_SP2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SP2, "SP2");
    lv_obj_set_style_text_color(ui_SP2, lv_color_hex(0xE8EEEF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SP2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SP3 = lv_label_create(ui_ViewDataScreen);
    lv_obj_set_width(ui_SP3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SP3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SP3, 120);
    lv_obj_set_y(ui_SP3, -30);
    lv_obj_set_align(ui_SP3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SP3, "SP3");
    lv_obj_set_style_text_color(ui_SP3, lv_color_hex(0xE8EEEF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SP3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NumSP1 = lv_label_create(ui_ViewDataScreen);
    lv_obj_set_width(ui_NumSP1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NumSP1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NumSP1, -120);
    lv_obj_set_y(ui_NumSP1, 0);
    lv_obj_set_align(ui_NumSP1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NumSP1, "0");
    lv_obj_set_style_text_color(ui_NumSP1, lv_color_hex(0xF5F9FA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NumSP1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NumSP2 = lv_label_create(ui_ViewDataScreen);
    lv_obj_set_width(ui_NumSP2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NumSP2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_NumSP2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NumSP2, "0");
    lv_obj_set_style_text_color(ui_NumSP2, lv_color_hex(0xF5F9FA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NumSP2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NumSP3 = lv_label_create(ui_ViewDataScreen);
    lv_obj_set_width(ui_NumSP3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NumSP3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NumSP3, 120);
    lv_obj_set_y(ui_NumSP3, 0);
    lv_obj_set_align(ui_NumSP3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NumSP3, "0");
    lv_obj_set_style_text_color(ui_NumSP3, lv_color_hex(0xF5F9FA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NumSP3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label25 = lv_label_create(ui_ViewDataScreen);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label25, -149);
    lv_obj_set_y(ui_Label25, 137);
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "HOME");
    lv_obj_set_style_text_color(ui_Label25, lv_color_hex(0xD5CFD3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label25, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeButton6 = lv_button_create(ui_ViewDataScreen);
    lv_obj_set_width(ui_HomeButton6, 103);
    lv_obj_set_height(ui_HomeButton6, 34);
    lv_obj_set_x(ui_HomeButton6, -168);
    lv_obj_set_y(ui_HomeButton6, 137);
    lv_obj_set_align(ui_HomeButton6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HomeButton6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_HomeButton6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_HomeButton6, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HomeButton6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HomeButton6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_HomeButton6, lv_color_hex(0x7B7B7B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_HomeButton6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_HomeButton6, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_HomeButton6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_HomeButton6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image26 = lv_image_create(ui_ViewDataScreen);
    lv_image_set_src(ui_Image26, &ui_img_home_50dp_e3e3e3_fill0_wght400_grad0_opsz48_png);
    lv_obj_set_width(ui_Image26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image26, -194);
    lv_obj_set_y(ui_Image26, 136);
    lv_obj_set_align(ui_Image26, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image26, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image26, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image26, 150);

    ui_ResetButton = lv_button_create(ui_ViewDataScreen);
    lv_obj_set_width(ui_ResetButton, 103);
    lv_obj_set_height(ui_ResetButton, 34);
    lv_obj_set_x(ui_ResetButton, 168);
    lv_obj_set_y(ui_ResetButton, 137);
    lv_obj_set_align(ui_ResetButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ResetButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ResetButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ResetButton, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ResetButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ResetButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ResetButton, lv_color_hex(0x7B7B7B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ResetButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ResetButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ResetButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ResetButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResetText = lv_label_create(ui_ViewDataScreen);
    lv_obj_set_width(ui_ResetText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ResetText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ResetText, 168);
    lv_obj_set_y(ui_ResetText, 137);
    lv_obj_set_align(ui_ResetText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ResetText, "RESET");
    lv_obj_set_style_text_color(ui_ResetText, lv_color_hex(0xD5CFD3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ResetText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_ViewDataScreen);
    lv_obj_set_width(ui_Panel1, 280);
    lv_obj_set_height(ui_Panel1, 140);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Panel1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x434548), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0x6C6868), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResetButton2 = lv_button_create(ui_Panel1);
    lv_obj_set_width(ui_ResetButton2, 103);
    lv_obj_set_height(ui_ResetButton2, 34);
    lv_obj_set_x(ui_ResetButton2, -69);
    lv_obj_set_y(ui_ResetButton2, 40);
    lv_obj_set_align(ui_ResetButton2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ResetButton2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ResetButton2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ResetButton2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ResetButton2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ResetButton2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ResetButton2, lv_color_hex(0x7B7B7B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ResetButton2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ResetButton2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ResetButton2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ResetButton2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResetButton1 = lv_button_create(ui_Panel1);
    lv_obj_set_width(ui_ResetButton1, 103);
    lv_obj_set_height(ui_ResetButton1, 34);
    lv_obj_set_x(ui_ResetButton1, 69);
    lv_obj_set_y(ui_ResetButton1, 40);
    lv_obj_set_align(ui_ResetButton1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ResetButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ResetButton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ResetButton1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ResetButton1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ResetButton1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ResetButton1, lv_color_hex(0x7B7B7B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ResetButton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ResetButton1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ResetButton1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ResetButton1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label24 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label24, 0);
    lv_obj_set_y(ui_Label24, -20);
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "Do you want to reset?");
    lv_obj_set_style_text_color(ui_Label24, lv_color_hex(0xECEFF1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label24, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResetText1 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_ResetText1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ResetText1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ResetText1, -69);
    lv_obj_set_y(ui_ResetText1, 40);
    lv_obj_set_align(ui_ResetText1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ResetText1, "Yes");
    lv_obj_set_style_text_color(ui_ResetText1, lv_color_hex(0xD5CFD3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ResetText1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResetText3 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_ResetText3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ResetText3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ResetText3, 69);
    lv_obj_set_y(ui_ResetText3, 40);
    lv_obj_set_align(ui_ResetText3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ResetText3, "No");
    lv_obj_set_style_text_color(ui_ResetText3, lv_color_hex(0xD5CFD3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ResetText3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_HomeButton6, ui_event_HomeButton6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ResetButton, ui_event_ResetButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ResetButton2, ui_event_ResetButton2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ResetButton1, ui_event_ResetButton1, LV_EVENT_ALL, NULL);

}

void ui_ViewDataScreen_screen_destroy(void)
{
    if(ui_ViewDataScreen) lv_obj_del(ui_ViewDataScreen);

    // NULL screen variables
    ui_ViewDataScreen = NULL;
    ui_Image25 = NULL;
    ui_ViewDatatext = NULL;
    ui_SP1 = NULL;
    ui_SP2 = NULL;
    ui_SP3 = NULL;
    ui_NumSP1 = NULL;
    ui_NumSP2 = NULL;
    ui_NumSP3 = NULL;
    ui_Label25 = NULL;
    ui_HomeButton6 = NULL;
    ui_Image26 = NULL;
    ui_ResetButton = NULL;
    ui_ResetText = NULL;
    ui_Panel1 = NULL;
    ui_ResetButton2 = NULL;
    ui_ResetButton1 = NULL;
    ui_Label24 = NULL;
    ui_ResetText1 = NULL;
    ui_ResetText3 = NULL;

}
