// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_VIEWDATASCREEN_H
#define UI_VIEWDATASCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ViewDataScreen
extern void ui_ViewDataScreen_screen_init(void);
extern void ui_ViewDataScreen_screen_destroy(void);
extern lv_obj_t * ui_ViewDataScreen;
extern lv_obj_t * ui_Image25;
extern lv_obj_t * ui_ViewDatatext;
extern lv_obj_t * ui_SP1;
extern lv_obj_t * ui_SP2;
extern lv_obj_t * ui_SP3;
extern lv_obj_t * ui_NumSP1;
extern lv_obj_t * ui_NumSP2;
extern lv_obj_t * ui_NumSP3;
extern lv_obj_t * ui_Label25;
extern void ui_event_HomeButton6(lv_event_t * e);
extern lv_obj_t * ui_HomeButton6;
extern lv_obj_t * ui_Image26;
extern void ui_event_ResetButton(lv_event_t * e);
extern lv_obj_t * ui_ResetButton;
extern lv_obj_t * ui_ResetText;
extern lv_obj_t * ui_Panel1;
extern void ui_event_ResetButton2(lv_event_t * e);
extern lv_obj_t * ui_ResetButton2;
extern void ui_event_ResetButton1(lv_event_t * e);
extern lv_obj_t * ui_ResetButton1;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_ResetText1;
extern lv_obj_t * ui_ResetText3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

